spring.application.name=mailing-service
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
spring.datasource.url=jdbc:postgresql://localhost:5432/mails
spring.datasource.username=postgres
spring.datasource.password=damilare
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.profiles.include=mail
spring.security.user.password=be8f6134-44d9-4716-b661-b93d62d2b61f
server.port=8081

